export interface StateLlcFee {
  state: string;
  filingFee: string;
  annualFee: string;
  website: string;
}

export const LLC_FEES_BY_STATE: StateLlcFee[] = [
  { state: "Alabama", filingFee: "$50", annualFee: "$0 (min $50 BPT)", website: "https://www.sos.alabama.gov/business-entities" },
  { state: "Alaska", filingFee: "$250", annualFee: "$100 (Biennial)", website: "https://www.commerce.alaska.gov/web/cbpl/Corporations.aspx" },
  { state: "Arizona", filingFee: "$50", annualFee: "$0", website: "https://www.azcc.gov/" },
  { state: "Arkansas", filingFee: "$45", annualFee: "$150 (Annual)", website: "https://www.sos.arkansas.gov/" },
  { state: "California", filingFee: "$70", annualFee: "$800 + $20 (Biennial)", website: "https://bizfileonline.sos.ca.gov/" },
  { state: "Colorado", filingFee: "$50", annualFee: "$10 (Annual)", website: "https://www.sos.state.co.us/pubs/business/main.htm" },
  { state: "Connecticut", filingFee: "$120", annualFee: "$80 (Annual)", website: "https://business.ct.gov/" },
  { state: "Delaware", filingFee: "$90", annualFee: "$300 (Annual)", website: "https://corp.delaware.gov/" },
  { state: "Florida", filingFee: "$125", annualFee: "$138.75 (Annual)", website: "https://dos.myflorida.com/sunbiz/" },
  { state: "Georgia", filingFee: "$100", annualFee: "$50 (Annual)", website: "https://ecorp.sos.ga.gov/" },
  { state: "Hawaii", filingFee: "$50", annualFee: "$15 (Annual)", website: "https://hbe.ehawaii.gov/documents/search.html" },
  { state: "Idaho", filingFee: "$100", annualFee: "$0", website: "https://sosbiz.idaho.gov/" },
  { state: "Illinois", filingFee: "$150", annualFee: "$75 (Annual)", website: "https://www.ilsos.gov/" },
  { state: "Indiana", filingFee: "$95", annualFee: "$30 (Biennial)", website: "https://inbiz.in.gov/" },
  { state: "Iowa", filingFee: "$50", annualFee: "$30 (Biennial)", website: "https://sos.iowa.gov/" },
  { state: "Kansas", filingFee: "$160", annualFee: "$50 (Annual)", website: "https://www.kansas.gov/businesscenter/" },
  { state: "Kentucky", filingFee: "$40", annualFee: "$15 (Annual)", website: "https://onestop.ky.gov/" },
  { state: "Louisiana", filingFee: "$100", annualFee: "$35 (Annual)", website: "https://geauxbiz.sos.la.gov/" },
  { state: "Maine", filingFee: "$175", annualFee: "$85 (Annual)", website: "https://www.maine.gov/sos/cec/corp/index.html" },
  { state: "Maryland", filingFee: "$100", annualFee: "$300 (Annual)", website: "https://egov.maryland.gov/BusinessExpress/" },
  { state: "Massachusetts", filingFee: "$500", annualFee: "$500 (Annual)", website: "https://corp.sec.state.ma.us/corpweb/CorpSearch/CorpSearch.aspx" },
  { state: "Michigan", filingFee: "$50", annualFee: "$25 (Annual)", website: "https://cofs.lara.state.mi.us/" },
  { state: "Minnesota", filingFee: "$155", annualFee: "$0", website: "https://mblsportal.sos.state.mn.us/" },
  { state: "Mississippi", filingFee: "$50", annualFee: "$0", website: "https://corp.sos.ms.gov/corp/portal/c/page/corpBusinessIdSearch/" },
  { state: "Missouri", filingFee: "$50", annualFee: "$0", website: "https://bsd.sos.mo.gov/" },
  { state: "Montana", filingFee: "$35", annualFee: "$20 (Annual)", website: "https://biz.sosmt.gov/" },
  { state: "Nebraska", filingFee: "$100", annualFee: "$13 (Biennial)", website: "https://www.nebraska.gov/sos/corp/corpsearch.cgi" },
  { state: "Nevada", filingFee: "$425", annualFee: "$350 (Annual)", website: "https://www.nvsilverflume.gov/" },
  { state: "New Hampshire", filingFee: "$100", annualFee: "$100 (Annual)", website: "https://quickstart.sos.nh.gov/" },
  { state: "New Jersey", filingFee: "$125", annualFee: "$75 (Annual)", website: "https://www.nj.gov/treasury/revenue/" },
  { state: "New Mexico", filingFee: "$50", annualFee: "$0", website: "https://portal.sos.state.nm.us/BFS/online/Account/Login" },
  { state: "New York", filingFee: "$200", annualFee: "$9 (Biennial)", website: "https://www.dos.ny.gov/corps/" },
  { state: "North Carolina", filingFee: "$125", annualFee: "$200 (Annual)", website: "https://www.sosnc.gov/" },
  { state: "North Dakota", filingFee: "$135", annualFee: "$50 (Annual)", website: "https://firststop.sos.nd.gov/" },
  { state: "Ohio", filingFee: "$99", annualFee: "$0", website: "https://bsportal.ohiosos.gov/" },
  { state: "Oklahoma", filingFee: "$100", annualFee: "$25 (Annual)", website: "https://www.sos.ok.gov/" },
  { state: "Oregon", filingFee: "$100", annualFee: "$100 (Annual)", website: "https://sos.oregon.gov/business/" },
  { state: "Pennsylvania", filingFee: "$125", annualFee: "$7 (Annual)", website: "https://www.dos.pa.gov/BusinessCharities/" },
  { state: "Rhode Island", filingFee: "$150", annualFee: "$50 (Annual)", website: "https://business.sos.ri.gov/" },
  { state: "South Carolina", filingFee: "$110", annualFee: "$0", website: "https://businessfilings.sc.gov/" },
  { state: "South Dakota", filingFee: "$150", annualFee: "$50 (Annual)", website: "https://sosenterprise.sd.gov/BusinessServices/Business/FilingSearch.aspx" },
  { state: "Tennessee", filingFee: "$300", annualFee: "$300 (Annual)", website: "https://tnbear.tn.gov/Ecommerce/FilingSearch.aspx" },
  { state: "Texas", filingFee: "$300", annualFee: "$0", website: "https://www.sos.state.tx.us/corp/business.shtml" },
  { state: "Utah", filingFee: "$59", annualFee: "$18 (Annual)", website: "https://corporations.utah.gov/" },
  { state: "Vermont", filingFee: "$125", annualFee: "$35 (Annual)", website: "https://www.sec.state.vt.us/corporations.aspx" },
  { state: "Virginia", filingFee: "$100", annualFee: "$50 (Annual)", website: "https://cis.scc.virginia.gov/" },
  { state: "Washington", filingFee: "$180", annualFee: "$60 (Annual)", website: "https://ccfs.sos.wa.gov/" },
  { state: "Washington, D.C.", filingFee: "$99", annualFee: "$300 (Biennial)", website: "https://corponline.dcra.dc.gov/" },
  { state: "West Virginia", filingFee: "$100", annualFee: "$25 (Annual)", website: "https://onestop.wv.gov/" },
  { state: "Wisconsin", filingFee: "$170", annualFee: "$25 (Annual)", website: "https://www.wdfi.org/corporations/" },
  { state: "Wyoming", filingFee: "$100", annualFee: "$60 (Annual)", website: "https://wyobiz.wyo.gov/Business/" }
];
